# Generated by Django 2.1.7 on 2019-04-15 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_movie1', models.IntegerField()),
                ('liked_movie2', models.IntegerField()),
                ('liked_movie3', models.IntegerField()),
                ('rec_movie1', models.IntegerField(blank=True)),
                ('rec_movie2', models.IntegerField(blank=True)),
                ('rec_movie3', models.IntegerField(blank=True)),
                ('rec_movie4', models.IntegerField(blank=True)),
                ('rec_movie5', models.IntegerField(blank=True)),
                ('rec_movie6', models.IntegerField(blank=True)),
                ('rec_movie7', models.IntegerField(blank=True)),
                ('rec_movie8', models.IntegerField(blank=True)),
                ('rec_movie9', models.IntegerField(blank=True)),
                ('rec_movie10', models.IntegerField(blank=True)),
                ('rec_movie11', models.IntegerField(blank=True)),
                ('rec_movie12', models.IntegerField(blank=True)),
                ('rec_movie13', models.IntegerField(blank=True)),
                ('rec_movie14', models.IntegerField(blank=True)),
                ('rec_movie15', models.IntegerField(blank=True)),
                ('rec_movie16', models.IntegerField(blank=True)),
                ('rec_movie17', models.IntegerField(blank=True)),
                ('rec_movie18', models.IntegerField(blank=True)),
                ('rec_movie19', models.IntegerField(blank=True)),
                ('rec_movie20', models.IntegerField(blank=True)),
                ('rec_movie21', models.IntegerField(blank=True)),
                ('rec_movie22', models.IntegerField(blank=True)),
                ('rec_movie23', models.IntegerField(blank=True)),
                ('rec_movie24', models.IntegerField(blank=True)),
                ('rec_movie25', models.IntegerField(blank=True)),
            ],
        ),
    ]
